name: Frontend Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, frontendUnitTests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test
